### ISSUE TITLE
Override toggle colors for specific buttons

### ISSUE THREAD

**Issue by Redsandro** [knownasilya/ember-toggle#126]
I'm curious if there's a better way than overriding the color values using custom css selectors and supplying a custom class name?

This is basically what I'm doing now:

```css
.x-toggle-flip-warn {
	.x-toggle-flip {
		&::before {
			background-color: #ffff00 !important;
		}
		&::after {
			background-color: #aaaaaa !important;
		}
	}
}
```
